//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SimpleEchoBot.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Bot
    {
        public int Id { get; set; }
        public int BotTypeId { get; set; }
        public string Name { get; set; }
        public System.DateTime DateCreated { get; set; }
        public System.DateTime DateUpdated { get; set; }
        public string CodeLocation { get; set; }
        public int EnvironmentId { get; set; }
        public bool Active { get; set; }
        public Nullable<int> OwnerUserId { get; set; }
        public Nullable<bool> Premier { get; set; }
        public Nullable<int> Subscribers { get; set; }
        public Nullable<int> BotDetailId { get; set; }
    
        public virtual BotType BotType { get; set; }
    }
}
