//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SimpleEchoBot.Data
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class StreambotEntities : DbContext
    {
        public StreambotEntities ()
            : base("name=StreambotEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Bot> Bots { get; set; }
        public virtual DbSet<BotType> BotTypes { get; set; }
        public virtual DbSet<EnvType> EnvTypes { get; set; }
    }
}
